In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import warnings 
warnings.filterwarnings('ignore')
import matplotlib.pyplot as plt

In [2]:
url=r"https://gist.githubusercontent.com/Thanatoz-1/9e7fdfb8189f0cdf5d73a494e4a6392a/raw/aaecbd14aeaa468cd749528f291aa8a30c2ea09e/iris_dataset.csv"

In [3]:
data=pd.read_csv(url)
data

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica
146,6.3,2.5,5.0,1.9,Iris-virginica
147,6.5,3.0,5.2,2.0,Iris-virginica
148,6.2,3.4,5.4,2.3,Iris-virginica
149,5.9,3.0,5.1,1.8,Iris-virginica

In [4]:
X=data.drop(columns='target')
X

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [5]:
y=data["target"]
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: target, Length: 150, dtype: object

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [8]:
X_train

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
73                 6.1               2.8                4.7               1.2
137                6.4               3.1                5.5               1.8
77                 6.7               3.0                5.0               1.7
111                6.4               2.7                5.3               1.9
33                 5.5               4.2                1.4               0.2
..                 ...               ...                ...               ...
113                5.7               2.5                5.0               2.0
17                 5.1               3.5                1.4               0.3
76                 6.8               2.8                4.8               1.4
21                 5.1               3.7                1.5               0.4
46                 5.1               3.8                1.6               0.2

[120 rows x 4 columns]

In [9]:
X_test

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
66                 5.6               3.0                4.5               1.5
108                6.7               2.5                5.8               1.8
26                 5.0               3.4                1.6               0.4
95                 5.7               3.0                4.2               1.2
105                7.6               3.0                6.6               2.1
58                 6.6               2.9                4.6               1.3
19                 5.1               3.8                1.5               0.3
38                 4.4               3.0                1.3               0.2
143                6.8               3.2                5.9               2.3
20                 5.4               3.4                1.7               0.2
55                 5.7               2.8                4.5               1.3
78                 6.0               2.9                4.5               1.5
115                6.4               3.2                5.3               2.3
91                 6.1               3.0                4.6               1.4
8                  4.4               2.9                1.4               0.2
22                 4.6               3.6                1.0               0.2
50                 7.0               3.2                4.7               1.4
116                6.5               3.0                5.5               1.8
99                 5.7               2.8                4.1               1.3
15                 5.7               4.4                1.5               0.4
68                 6.2               2.2                4.5               1.5
35                 5.0               3.2                1.2               0.2
112                6.8               3.0                5.5               2.1
6                  4.6               3.4                1.4               0.3
102                7.1               3.0                5.9               2.1
94                 5.6               2.7                4.2               1.3
130                7.4               2.8                6.1               1.9
44                 5.1               3.8                1.9               0.4
144                6.7               3.3                5.7               2.5
148                6.2               3.4                5.4               2.3

In [10]:
y_train

73     Iris-versicolor
137     Iris-virginica
77     Iris-versicolor
111     Iris-virginica
33         Iris-setosa
            ...
113     Iris-virginica
17         Iris-setosa
76     Iris-versicolor
21         Iris-setosa
46         Iris-setosa
Name: target, Length: 120, dtype: object

In [11]:
y_test

66     Iris-versicolor
108     Iris-virginica
26         Iris-setosa
95     Iris-versicolor
105     Iris-virginica
58     Iris-versicolor
19         Iris-setosa
38         Iris-setosa
143     Iris-virginica
20         Iris-setosa
55     Iris-versicolor
78     Iris-versicolor
115     Iris-virginica
91     Iris-versicolor
8          Iris-setosa
22         Iris-setosa
50     Iris-versicolor
116     Iris-virginica
99     Iris-versicolor
15         Iris-setosa
68     Iris-versicolor
35         Iris-setosa
112     Iris-virginica
6          Iris-setosa
102     Iris-virginica
94     Iris-versicolor
130     Iris-virginica
44         Iris-setosa
144     Iris-virginica
148     Iris-virginica
Name: target, dtype: object

In [12]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr

LogisticRegression()

In [13]:
lr.fit(X_train,y_train)

LogisticRegression()

In [14]:
y_predict=lr.predict(X_test)

In [15]:
lr.fit(X_train,y_train)

LogisticRegression()

In [16]:
accuracy_score(y_predict,y_test)

NameError: name 'accuracy_score' is not defined

In [23]:
url=r'https://gist.githubusercontent.com/ryanorsinger/0c702f67dfe59346cd4677cd24f7aec7/raw/429f0d47856670e57b31d1f78a1abc54c889c7ca/tips.csv'

In [24]:
data=pd.read_csv(url)
data

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [37]:
dt1=data.drop(columns=['sex','smoker','day','time'])
dt1

     total_bill   tip  size
0         16.99  1.01     2
1         10.34  1.66     3
2         21.01  3.50     3
3         23.68  3.31     2
4         24.59  3.61     4
..          ...   ...   ...
239       29.03  5.92     3
240       27.18  2.00     2
241       22.67  2.00     2
242       17.82  1.75     2
243       18.78  3.00     2

[244 rows x 3 columns]

In [38]:
X=dt1.drop(columns='tip')
X

     total_bill  size
0         16.99     2
1         10.34     3
2         21.01     3
3         23.68     2
4         24.59     4
..          ...   ...
239       29.03     3
240       27.18     2
241       22.67     2
242       17.82     2
243       18.78     2

[244 rows x 2 columns]

In [39]:
y=dt1["tip"]
y

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ...
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

In [40]:
from sklearn.model_selection import train_test_split

In [41]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [48]:
X_train

     total_bill  size
201       12.74     2
89        21.16     2
101       15.38     2
32        15.06     2
57        26.41     2
..          ...   ...
166       20.76     2
119       24.08     4
219       30.14     4
112       38.07     3
106       20.49     2

[195 rows x 2 columns]

In [49]:
X_test

     total_bill  size
50        12.54     2
183       23.17     4
185       20.69     5
16        10.33     3
69        15.01     2
207       38.73     4
147       11.87     2
84        15.98     2
107       25.21     2
163       13.81     2
148        9.78     2
5         25.29     4
80        19.44     2
115       17.31     2
92         5.75     2
209       12.76     2
204       20.53     4
128       11.38     2
14        14.83     2
110       14.00     2
217       11.59     2
140       17.47     2
7         26.88     4
198       13.00     2
74        14.73     2
72        26.86     2
218        7.74     2
44        30.40     4
174       16.82     2
86        13.03     2
48        28.55     3
176       17.89     2
151       13.13     2
190       15.69     2
178        9.60     2
215       12.90     2
164       17.51     2
36        16.31     3
12        15.42     2
96        27.28     2
177       14.48     2
65        20.08     3
123       15.95     2
98        21.01     2
214       28.17     3
40        16.04     3
99        12.46     2
235       10.07     2
31        18.35     4

In [50]:
y_train

201    2.01
89     3.00
101    3.00
32     3.00
57     1.50
       ...
166    2.24
119    2.92
219    3.09
112    4.00
106    4.06
Name: tip, Length: 195, dtype: float64

In [51]:
y_test

50     2.50
183    6.50
185    5.00
16     1.67
69     2.09
207    3.00
147    1.63
84     2.03
107    4.29
163    2.00
148    1.73
5      4.71
80     3.00
115    3.50
92     1.00
209    2.23
204    4.00
128    2.00
14     3.02
110    3.00
217    1.50
140    3.50
7      3.12
198    2.00
74     2.20
72     3.14
218    1.44
44     5.60
174    4.00
86     2.00
48     2.05
176    2.00
151    2.00
190    1.50
178    4.00
215    1.10
164    3.00
36     2.00
12     1.57
96     4.00
177    2.00
65     3.15
123    2.00
98     3.00
214    6.50
40     2.24
99     1.50
235    1.25
31     2.50
Name: tip, dtype: float64

In [53]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr

LinearRegression()

In [54]:
lr.fit(X_train,y_train)

LinearRegression()

In [55]:
y_predict=lr.predict(X_test)

In [60]:
from sklearn.metrics import r2_score

In [61]:
r2_score(y_predict,y_test)

-1.0707517885099591